server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          spring-action-client-id:
            provider: spring-action-client-provider
            client-id: spring-action-client
            client-secret: secret
            authorization-grant-type: client_credentials
            client-name: spring-action-client-name
            scope: ingredients.read
        provider:
          spring-action-client-provider:
            issuer-uri: http://auth-server:9000